Repository THE-SOPT-30th-DaangnMarket-14/Daangn-Android, pull requests merged in 2022-06, with the labels that each got.

#16 [FEAT] #13 글쓰기 뷰 서버연결 MultiPart
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/daangnmarket_android/data/ServiceCreator.kt
  app/src/main/java/org/sopt/daangnmarket_android/data/api/WriteService.kt
  app/src/main/java/org/sopt/daangnmarket_android/response/ResponseWrite.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/WriteFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/fragment_write.xml
Labels: question, 🍀유리🍀

#18 [FEAT] #17 메인 뷰 서버연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/data/ItemData.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/data/ItemService.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/data/ResponseItem.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/data/ServiceCreator.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/main/HomeFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/main/adapter/ItemAdapter.kt
  app/src/main/res/drawable/shape_image.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/values/strings.xml
Labels: question, 🍎다희🍎

#20 [FEAT] #19 - 합동세미나 마무리
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/daangnmarket_android/data/ServiceCreator.kt
  app/src/main/java/org/sopt/daangnmarket_android/data/api/ItemService.kt
  app/src/main/java/org/sopt/daangnmarket_android/data/response/ResponseItem.kt
  app/src/main/java/org/sopt/daangnmarket_android/domain/model/ItemData.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/data/ServiceCreator.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/main/HomeFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/main/adapter/ItemAdapter.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/WriteFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 🚙 승현 🚙, feature
