Repository THE-SOPT-30th-DaangnMarket-14/Daangn-Android, pull requests merged in 2022-05, with the labels that each got.

#4 [FEAT] #2 - WriteActivity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/WriteActivity.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/WriteFragment.kt
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/values/strings.xml
Labels: question, 🍀유리🍀

#6 [FEAT] Image Picker
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/daangnmarket_android/application/App.kt
  app/src/main/java/org/sopt/daangnmarket_android/data/repository/GalleryRepositoryImpl.kt
  app/src/main/java/org/sopt/daangnmarket_android/di/RepositoryModule.kt
  app/src/main/java/org/sopt/daangnmarket_android/di/SingletonModule.kt
  app/src/main/java/org/sopt/daangnmarket_android/domain/model/GalleryImage.kt
  app/src/main/java/org/sopt/daangnmarket_android/domain/repository/GalleryRepository.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/adapter/GalleryAdapter.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/adapter/WriteAdapter.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/gallery/GalleryActivity.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/GalleryFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/WriteActivity.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/WriteFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/viewmodel/WriteViewModel.kt
  app/src/main/java/org/sopt/daangnmarket_android/util/ContextUtil.kt
  app/src/main/java/org/sopt/daangnmarket_android/util/ConvertExtensions.kt
  app/src/main/java/org/sopt/daangnmarket_android/util/GalleryDecoration.kt
  app/src/main/java/org/sopt/daangnmarket_android/util/GalleryItemAnimator.kt
  app/src/main/java/org/sopt/daangnmarket_android/util/SingleLiveEvent.kt
  app/src/main/java/org/sopt/daangnmarket_android/util/WriteDecoration.kt
  app/src/main/java/org/sopt/daangnmarket_android/util/WriteItemAnimator.kt
  app/src/main/res/drawable/circle_orange.xml
  app/src/main/res/drawable/circle_white_stroke.xml
  app/src/main/res/drawable/rectangle_gray_round_4.xml
  app/src/main/res/drawable/rectangle_orange_border_2.xml
  app/src/main/res/layout/activity_gallery.xml
  app/src/main/res/layout/fragment_gallery.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_camera.xml
  app/src/main/res/layout/item_gallery.xml
  app/src/main/res/layout/item_write_camera.xml
  app/src/main/res/layout/item_write_image.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🚙 승현 🚙, feature

#9 Update README.md
  README.md
Labels: documentation, 🚙 승현 🚙

#10 [FEAT] #2 작성하기 Databinding 적용
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/WriteFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: help wanted, question, 🍀유리🍀

#11 [FIX, FEAT] #7 ImagePicker 수정 및 부족한 구현사항 보완
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/daangnmarket_android/ui/adapter/GalleryAdapter.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/adapter/WriteAdapter.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/gallery/GalleryActivity.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/GalleryFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/view/write/WriteFragment.kt
  app/src/main/java/org/sopt/daangnmarket_android/ui/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_write_image.xml
  app/src/main/res/values/strings.xml
Labels: bug, 🚙 승현 🚙, feature
